### PR TITLE
default.xml: add meta-ti

### PR DESCRIPTION
**Pull request by andrey-konovalov**
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>

### CODE REVIEW

**Comment by andrey-konovalov** [comment]
This change is required, but building rpb-console-image is still failing. Now with:
-----8<-----
ERROR: /home/oe-build/test-build/build-rpb/conf/../../layers/meta-ti/recipes-ti/devtools/ti-cgt6x_8.1.0.bb: Error executing a python function in <code>:
<snip>
     0019:        tunes = bb.data.getVar("TUNE_FEATURES", d, 1)
<snip>
Exception: AttributeError: 'module' object has no attribute 'getVar'
-----8<-----

**Comment by andrey-konovalov** [comment]
the full error message: https://pastebin.linaro.org/view/48bfe51f

**Comment by andrey-konovalov** [comment]
let's hold this change for now

**Comment by koenkooi** [comment]
FWIW, RP has posted a sed script to fix all those getvars:

```
sed -e 's:\(\.getVar([^,()]*\)):\1, False):g' -i `grep -ril getVar *`
```

**Comment by koenkooi** [comment]
Sorry, wrong sed script. This one is for bb.data -> d:

```
sed \
 -e 's:bb.data.\(expand([^,()]*\), *\([^) ]*\) *):\2.\1):g' \
 -i `grep -ril bb.data.expand *`
```

Change that to match getVar/setVar

**Comment by andrey-konovalov** [comment]
The patch has already been submitted. Not merged yet to to bad subject line:
https://lists.yoctoproject.org/pipermail/meta-ti/2016-December/009299.html

**Comment by andrey-konovalov** [comment]
The getVar fix has been merged into meta-ti/master:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-ti/commit/?id=d8827afedc66b610f1fc9c5990bc4271917643b6

**Pull request merged**
