### PR TITLE
Switch RPB builds to use meta-arm-toolchain layer

### PR DESCRIPTION
**Pull request by b49020**
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>

### CODE REVIEW

**Comment by ndechesne** [comment]
since meta-arm doesn't have a zeus branch, i don't think we should use meta-arm-toolchain for zeus yet. using meta-arm/master will eventually fail in our zeus builds.. so unless meta-arm commits to zeus branch, i would prefer that we only do the change for our master branch builds.

**Comment by b49020** [comment]
Ok makes sense. So we should keep using meta-linaro-toolchain for zeus until meta-arm commits to zeus branch, correct?

**Comment by ndechesne** [comment]
yes, that's what I am proposing.

**Comment by b49020** [comment]
Ok, will close this PR.

**Pull request closed without merging**
