### PR TITLE
mixed-build.md: instructions for doing "32-bit userland/64-bit kernel" builds

### PR DESCRIPTION
**Pull request by andrey-konovalov**
This documentation complements commit 55296c49f4a8f12f55d4b7480e4be40ec3d4873a "setup: Add helper command to build multiple images".

### CODE REVIEW

**Comment by fboudra** [comment]
the documentation goes usually to linaro github project, under documentation: https://github.com/Linaro/documentation

**Comment by andrey-konovalov** [comment]
Thanks, Fathi!
Looks like these instructions could be added to or referenced from https://github.com/Linaro/documentation/blob/master/Reference-Platform/CECommon/OE.md

Robert,
If you suggest me a place at https://github.com/Linaro/documentation where I should put these instruction to, I could prepare a merge request against https://github.com/Linaro/documentation/tree/master.

And a nitpick. I did check https://github.com/Linaro/documentation before making this pull request, but that time haven't noticed this OE.md page - it is properly located under CECommon, but I've got to it through Reference-Platform/RPOfficial/README.md -> ""Quick Start / Consumer Edition /HiKey" (Reference-Platform/RPOfficial/ConsumerEdition/HiKey/README.md) -> "Access OpenEmbedded build from source instructions here". I.e. I had to go through HiKey specific instructions to get to CECommon/OE.md ones. Is there a different link to OE.md from a more generic (not HiKey specific) page?

**Comment by sdrobertw** [comment]
Hello @andrey-konovalov I am very sorry for the delay.

Based on my understanding, we are looking for a place to host more robust build instructions for OE on both HiKey and DB410c.

If this is the case, we have a document setup in the github.com/Linaro/documentation repository.

**Please visit:** [OE.md](https://github.com/Linaro/documentation/blob/master/Reference-Platform/CECommon/OE.md)

**located at** https://github.com/Linaro/documentation/blob/master/Reference-Platform/CECommon/OE.md

Ideally, it would be nice to expand on this document. Focusing on what building OE for multiple 96Boards have in common and branching out to other documents for things they do not have in common.

For instance, package dependencies and build process (on linux host) is fairly similar for both DB410c and HiKey, flashing the images on the other hand can differ. 

If we can find a way to add this information to the OE.md file, this would be ideal.

Thoughts?

If you have any questions that need immediate attention, please feel free to reach out on IRC(channel #96boards) or Google Hangouts:

IRC: sdrobertw
Google Hangouts: robert.wolff@linaro.org

Thanks for your contributions! Once again, I am sorry for the late response.

**Comment by andrey-konovalov** [comment]
The instructions have been merged into Linaro/documentation. Closing.

**Pull request closed without merging**
