### PR TITLE
Contrib/twoerner/002 namespace

### PR DESCRIPTION
**Pull request by twoerner**
i'm not sure if this works for you. this is a second pull request, relative to my first pull request from earlier to day (contrib/twoerner/001_trap). that commit is included in this branch too since this commit is based on it (so it can't be based on the pristine jethro branch since that wouldn't make sense)

### CODE REVIEW

**Comment by ndechesne** [comment]
honestly.. i think we are crossing the "it is over engineered' line.. i can see what you are trying to do.. but in my opinion that makes the script more complex/ugly than it should.. 

i would like to hear what @koenkooi  or @fboudra have to say.. i am not strictly opposed to such changes.. but it hurts my 'KISS principle"..

**Comment by twoerner** [comment]
earlier today, in our google chat hangout, you said something along the lines of "we should be cautious with the variables we create since they could be in-use already". this patch is a response to that statement. if you look at my original set of patches from last weekend i didn't have any such namespace patch. i thought it was important to you, so i bumped it up in priority :-)

if it's in the "crazy" territory feel free to reject it :-)

**Comment by twoerner** [comment]
i guess github doesn't have any concept of a "patch series". i can't figure out a clean way to send a set of patches that depend on each other. i'll just have to send one or two at a time and await your review.

**Comment by ndechesne** [comment]
right, and in the same chat , i said "on the other hand.. i don't think we should over engineer that too much.. and keep it simple.. if you have ideas to improve without making it too uggly, maybe we can take that.. "

;-)

that's why I am trying to get others feedback on this one..

**Comment by twoerner** [comment]
"keep it simple?!" that's the sort of crazy-talk i tend to ignore!! ;-)

on a serious note, the question i'd like to ask is: is the whole idea of an identifier namespace the issue, or is it the one i chose (i.e. '__rpb_')? what if all the identifiers were uppercase and simply had a lowercase 'r' at the start? maybe that would be better? in retrospect the '__rpb_' is a bit over the top.

**Pull request closed without merging**
