### PR TITLE
Switch RPB builds to use meta-arm-toolchain layer

### PR DESCRIPTION
**Pull request by b49020**
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>

### CODE REVIEW

**Comment by ndechesne** [comment]
hi @b49020 , looks like this was never merged.. so we are still using our own copy of gcc-arm recipes in meta-linaro.. can you please check this PR, it says there are conflicts. Then we can merge it? would be good to merge before we branch for next release..

**Comment by b49020** [comment]
@ndechesne conflicts has been resolved, please go ahead with the merge.

**Comment by ndechesne** [comment]
hmm. i would prefer if you do a proper rebase. the 2nd commit here doesn't make too much sense. can you please check again?

**Comment by b49020** [comment]
Ah, sorry I didn't realize that while playing with github capability to resolve conflicts. Sure will do a proper rebase.

**Comment by b49020** [comment]
Rebased.

**Comment by ndechesne** [comment]
thanks. meta-arm has also merged the change to switch from SVN to tarball.

**Pull request merged**
