### PR TITLE
setup-environment-internal: use a cleanup trap

### PR DESCRIPTION
**Pull request by twoerner**
Install a trap handler to cleanup all defined objects, even in the case of an
early return due to error.

Signed-off-by: Trevor Woerner <twoerner@gmail.com>

### CODE REVIEW

**Comment by ndechesne** [comment]
it likely needs to be rebased. also I would prefer if you can submit smaller changes. this is a large pull request with many unrelated changes.

**Comment by twoerner** [comment]
In this way I find github confusing and annoying. Every time I update my jethro branch, github just keeps updating the one pull request I made to add the newest commit. Originally I pushed one commit (cleanup trap) and created a pull request, then I kept working on my jethro branch and every time I pushed, github added each commit to the existing pull request.

The only 2 solutions I can think of are:
1) to only push one change at a time and have to wait for someone to review it before sending the next
2) to setup several branches and push them all individually, but that wouldn't work well because each branch would depend on the other and the reviewer would have to know in which order to review them

:-(

**Comment by ndechesne** [comment]
github uses 'branch name' as the reference for a pull request.

so once you've submitted on pull request from 'branch_X' then you shouldn't
update branch_X, unless if you want to update the pull request (per review).

if you have many changes to make including fixes/cosmetic and new features,
i still recommend you split them sequentially.. however you do it, the time
it will take us to review and test will be the same.. a quick fix can be
merged quickly, larger changes will take more time..

github pull requests aren't very nicely implemented, i agree.. and i think
most people would agree..

my recommendation: make a branch for each new 'pull request', don't use the
'target' branch name. and don't mix fixes and features (or 2 features) into
1 pull request.

**Comment by twoerner** [comment]
okay. i'll number them so you'll know how to apply them without conflict (but later patches might conflict with the pristine branch until the ones before it are applied, if they're acceptable)

**Pull request closed without merging**
